[tool.poetry.dependencies]
python = "^3.11"
gunicorn = "^20.1.0"
flask = "^2.0.0"
selenium = "^4.0.0"
beautifulsoup4 = "^4.10.0"
flask_cors = "^3.1.1"
python-dotenv = "^0.19.0"
undetected-chromedriver = "^3.1.0"
