services:
  - type: web
    name: student-dashboard-backend
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg2
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      apt-get update
      apt-get install -y google-chrome-stable
    startCommand: gunicorn app:app --workers=1 --threads=2 --timeout=120
    runtime: python
    region: oregon
    plan: free
    pythonVersion: 3.10
    envVars:
      - key: RENDER
        value: true
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
