services:
  - type: web
    name: student-dashboard-backend
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn app:app
    runtime: python
    region: oregon
    plan: free
    pythonVersion: 3.10
    envVars:
      - key: RENDER
        value: true
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
